export enum EInputType {
  TEXT = "TEXT",
  EMAIL = "EMAIL",
  PHONE = "PHONE",
  PASSWORD = "PASSWORD",
  SEARCH = "SEARCH",
  DROPDOWN = "DROPDOWN",
  DATEPICKER = "DATEPICKER",
  AUTOCOMPLETE = "AUTOCOMPLETE",
}
